i5_object_name=SVIZZERA VOTATZIONE POPOLARE COMUNI INIZIATIVA "NO A UNA SVIZZERA DA 10 MILIONI"
i55_date_created=20260614
i120_caption=INFOGRAPHIE - Votatzione popolare del 14 giugno 2026 - Iniziativa "No a una Svizzera da 10 milioni". Questa infografica è stata creata automaticamente dal robot di scrittura Lena.
i103_original_transmission_reference=
i90_city=
i100_country_code=CHE
i15_category=N
i105_headline=Politica
i40_special_instructions=L'infografica può essere ottenuta nei formati grafici EPS e SVG. Questa infografica è stata creata automaticamente dal robot di scrittura Lena.
i110_credit=KEYSTONE
i115_source=KEYSTONE
i80_byline=Lena
i122_writer=Lena
